"""information-hub — dataset store (storage layer).

Writes the three-way collection store:

  raws/     AI output data frame per run (UTC filename) — audit + dedup ref
  preview/  human .md per record (canonical file under the primary layer)
  data-set/ machine .json per record (canonical file under the primary layer)

Canonical records live once (no duplication); classification layers are
generated by :mod:`src.storage.indexer`.

Role: both phases — consumed by main and storage.indexer.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from src.render.markdown import record_to_markdown


class Store:
    def __init__(self, data_dir: Path):
        base = Path(data_dir)
        self.collections = base / "collections"
        self.raws = self.collections / "raws"
        self.preview = self.collections / "preview"
        self.data_set = self.collections / "data-set"
        for d in (self.raws, self.preview, self.data_set):
            d.mkdir(parents=True, exist_ok=True)

    # ---- raws (AI output data frame) --------------------------------
    def write_raw_run(self, run_timestamp: str, records: list[dict[str, Any]]) -> Path:
        """Write the raw AI output frame for one run (UTC timestamp filename)."""
        safe = run_timestamp.replace(":", "-")
        path = self.raws / f"{safe}.json"
        frame = {
            "run_timestamp": run_timestamp,
            "items": records,
            "item_count": len(records),
        }
        path.write_text(json.dumps(frame, indent=2, ensure_ascii=False) + "\n",
                        encoding="utf-8")
        return path

    # ---- canonical record (data-set .json + preview .md) ------------
    def write_record(self, record: dict[str, Any], primary_layer_value: str) -> Path:
        """Store one record: data-set/<layer>/<key>.json + preview/<layer>/<key>.md."""
        layer = primary_layer_value or record.get("topic", "misc")
        key = record["key"]
        json_dir = self.data_set / layer
        md_dir = self.preview / layer
        json_dir.mkdir(parents=True, exist_ok=True)
        md_dir.mkdir(parents=True, exist_ok=True)

        json_path = json_dir / f"{key}.json"
        json_path.write_text(json.dumps(record, indent=2, ensure_ascii=False) + "\n",
                             encoding="utf-8")

        md_path = md_dir / f"{key}.md"
        md_path.write_text(record_to_markdown(record) + "\n", encoding="utf-8")
        return json_path

    # ---- readers (used by indexer/query) ------------------------------
    def iter_records(self) -> list[dict[str, Any]]:
        """Load every canonical .json record across all collections."""
        records: list[dict[str, Any]] = []
        for path in sorted(self.data_set.rglob("*.json")):
            try:
                records.append(json.loads(path.read_text(encoding="utf-8")))
            except (json.JSONDecodeError, OSError):
                continue
        return records
